### ISSUE TITLE
Published package missing code

### ISSUE THREAD

**Issue by txase** [hjdhjd/myq#3]
**Describe The Problem:**
I installed this package from npm as '@hjdhjd/myq'. I then tried to use it, but received the following error:

```
Runtime.ImportModuleError: Error: Cannot find module '/var/task/node_modules/@hjdhjd/myq/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at _loadUserApp (/var/runtime/UserFunction.js:100:13)
    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)
    at Object.<anonymous> (/var/runtime/index.js:43:30)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

**To Reproduce:**
Require the package into a script, like the following, and run it:

```JS
const { myQApi } = require('@hjdhjd/myq');
```

**Logs:**

N/A

**Screenshots:**

N/A

**Comment by txase** [comment]
Oh, the package is missing all source code. Here's a listing of the package files after I ran `npm install`:

```zsh
% ls node_modules/@hjdhjd/myq 
LICENSE.md      README.md       package.json
```

**Comment by hjdhjd** [comment]
Not sure what version of node or npm you’re using…the package definitely compiles and is correctly there. :smile:

It’s in production use elsewhere already. If you look at the NPM registry:

https://www.npmjs.com/package/@hjdhjd/myq

You’ll see there are 18 files in the install…so not sure what’s going on in your specific install, but it **does** install correctly.

**Comment by txase** [comment]
Huh, it looks right after I ran `npm install npm@latest -g`. Either I had a buggy version before (I'm not sure what version it was), or it had somehow been corrupted. Sorry for the noise!
